### ISSUE TITLE
Dependency missing from package.json

### ISSUE THREAD

**Issue by wolfd** [dy/point-cluster#6]
https://github.com/dy/point-cluster/blob/bdda757def9481be00cb886298e48c0929ee5186/quad.js#L14

`defined` should be defined in package.json. I suspect it is a [phantom dependency](https://rushjs.io/pages/advanced/phantom_deps/).

**Comment by dy** [comment]
Thanks!

**Comment by wolfd** [comment]
Amazing response time! Thank you!
