### ISSUE TITLE
Oops, another phantom dependency

### ISSUE THREAD

**Issue by wolfd** [dy/point-cluster#7]
[I didn't notice last time](https://github.com/dy/point-cluster/issues/6) but it also looks like `pick-by-alias` is missing from dependencies.

https://github.com/dy/point-cluster/blob/bdda757def9481be00cb886298e48c0929ee5186/quad.js#L13

Sorry for not noticing last time!

**Comment by wolfd** [comment]
I'm pretty sure this is the only other one. I have this working in my project with my [`pnpmfile.js`](https://pnpm.js.org/en/pnpmfile) looking like this:
```javascript
"use strict";
module.exports = {
  hooks: { readPackage }
};

function readPackage(pkg) {
  if (pkg.name === "point-cluster") {
    pkg.dependencies["pick-by-alias"] = "^1.2.0";
  }
  return pkg;
}

```

**Comment by dy** [comment]
Thanks!
